### ISSUE TITLE
Starting

### ISSUE THREAD

**Issue by bitcoinmeetups** [ytmytm/c64-lng#4]
Hi,

I'm Mr. FromAfar, a very friendly guy.

Nice to see some activity with Lunix again. Hope you can develop it further. If you can add basic internet capabilities that work through vice emulator that would be top notch.

Question: 

I have tested Lunix before on another computer but I don't remember how to start it. It was a sys command, wasn't it? The 2004 version extracts a bunch of stuff on my machine and then it just says ready and run doesn't do anything.

**Comment by ytmytm** [comment]
transfer lng.c64 to your Commodore64, insert a empty (formatted) disk
in drive 8 and run it, it will create a (hopefully :) working
LUnix disk

Run LUnix by loading "loader",8 + run

If this doe not work (maybe, because you want to use a different
set of boot.c64/lunix.c64 files) try it by hand:

load "boot.c64",8,1
...
load "lunix.c64",8,1
...
sys 4096

**Comment by bitcoinmeetups** [comment]
Ing.c64? Or do you mean Ing.d64? Where do I get it, do you have a link?
